### ISSUE TITLE
TODO: Re write README

### ISSUE THREAD

**Issue by B4kedBr3ad** [B4kedBr3ad/twitter-blocker#3]
Rewrote the execution method and package installation as it is difficult to understand

**Comment by B4kedBr3ad** [comment]
maybe change package manager npm -> yarn

**Comment by B4kedBr3ad** [comment]
i'm considering the possibility of finishing the code i created for myself, which i'm testing to like certain people, and incorporating it into the module

**Comment by B4kedBr3ad** [comment]
# 1024% will change
- [ ] rewrite README.md
- [ ] rewrite README-ja.md
 
# may be change / add
- [ ] add new module
  - [ ] tweet
  - [ ] delete tweet
  - [ ] mass likes
  - [ ] mass retweets

**Comment by B4kedBr3ad** [comment]
Temporary close because complete rewrite README and change package manager
